@Demo_HostAddress = http://localhost:5092

GET {{Demo_HostAddress}}/error/400
Accept: application/json

###

GET {{Demo_HostAddress}}/error/401
Accept: application/json

###

GET {{Demo_HostAddress}}/error/402
Accept: application/json

###

GET {{Demo_HostAddress}}/error/403
Accept: application/json

###

GET {{Demo_HostAddress}}/error/404
Accept: application/json

###

GET {{Demo_HostAddress}}/error/405
Accept: application/json

###

GET {{Demo_HostAddress}}/error/406
Accept: application/json

###

GET {{Demo_HostAddress}}/error/407
Accept: application/json

###

GET {{Demo_HostAddress}}/error/408
Accept: application/json

###

GET {{Demo_HostAddress}}/error/409
Accept: application/json

###

GET {{Demo_HostAddress}}/error/410
Accept: application/json

###

GET {{Demo_HostAddress}}/error/411
Accept: application/json

###

GET {{Demo_HostAddress}}/error/412
Accept: application/json

###

GET {{Demo_HostAddress}}/error/413
Accept: application/json

###

GET {{Demo_HostAddress}}/error/414
Accept: application/json

###

GET {{Demo_HostAddress}}/error/415
Accept: application/json

###

GET {{Demo_HostAddress}}/error/416
Accept: application/json

###

GET {{Demo_HostAddress}}/error/417
Accept: application/json

###

GET {{Demo_HostAddress}}/error/421
Accept: application/json

###

GET {{Demo_HostAddress}}/error/422
Accept: application/json

###

GET {{Demo_HostAddress}}/error/423
Accept: application/json

###

GET {{Demo_HostAddress}}/error/424
Accept: application/json

###

GET {{Demo_HostAddress}}/error/426
Accept: application/json

###

GET {{Demo_HostAddress}}/error/500
Accept: application/json

###

GET {{Demo_HostAddress}}/error/501
Accept: application/json

###

GET {{Demo_HostAddress}}/error/502
Accept: application/json

###

GET {{Demo_HostAddress}}/error/503
Accept: application/json

###

GET {{Demo_HostAddress}}/error/504
Accept: application/json

###

GET {{Demo_HostAddress}}/error/505
Accept: application/json

###

GET {{Demo_HostAddress}}/error/506
Accept: application/json

###

GET {{Demo_HostAddress}}/error/507
Accept: application/json

###

GET {{Demo_HostAddress}}/error/508
Accept: application/json

###

GET {{Demo_HostAddress}}/error/510
Accept: application/json

###

GET {{Demo_HostAddress}}/error/511
Accept: application/json

###

GET {{Demo_HostAddress}}/error/0
Accept: application/json

###
